org.gradle.jvmargs=-Xmx720m -XX:MaxMetaspaceSize=420m -XX:+UseSerialGC -XX:ReservedCodeCacheSize=80m -Dfile.encoding=UTF-8 -Dorg.gradle.logging.level=lifecycle
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.configureondemand=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=false
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
ksp.incremental=false
